[package]
name = "lending"
version = "1.0.0"
authors = []

[addresses]
alcove = "0x1140fb62f9e9a358217001353ff184c96a5b04f8c601b35048fa8485e612f499"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
